project_id = "eepkixxqvelppxzfwoin"

[functions.extract-property-data]
verify_jwt = false

[functions.search-properties]
verify_jwt = false

[functions.evaluate-property-scores]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.ping]
verify_jwt = false

[functions.test-extract]
verify_jwt = false

[functions.simple-extract]
verify_jwt = false

[functions.simple-score]
verify_jwt = false